### ISSUE TITLE
when load multiple dcm files, only 2 of these loaded correctly

### ISSUE THREAD

**Issue by ShannonZ** [cylab-tw/bluelight#40]
[Here](https://drive.google.com/file/d/1FLb8IJgrpA8D2giFaJLOexMDW1rtNgYB/view?usp=sharing) is the images for reproduction.
When load the 16 dicom files, only the first and the last one were loaded correctly.

**Comment by cylien** [comment]
Since those images have the same InstanceNumber, the sort order relies on the InstanceNumber. I suspect that those images were processed like de-identification might have caused the issue, leading to the slides displaying incorrectly.

To fix this problem, we will use multi-level sorting based on InstanceNumber and SOP Instance UID.

However, I suggest you check whether the process is correct, as it may have violated the correctness of the DICOM format, resulting in many tags having no value and wrong values.

**Comment by ShannonZ** [comment]
The Instance Number is not a must for legal DICOM files. [Ref](https://stackoverflow.com/questions/32681865/same-instance-number-for-two-dicom-image-in-a-single-series)

Any easy solutions for the immediate problem?

**Comment by birdeggb2777** [comment]
@ShannonZ
Fixed! Please try again.

**Comment by ShannonZ** [comment]
This solved my problem. Great THX!
